<a href="https://colab.research.google.com/github/Jung-ha1/220302_github_io/blob/main/2_%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC_(%EB%94%A5%EB%9F%AC%EB%8B%9D_%EC%9D%B4%EC%A7%84%2C_%EB%8B%A4%EC%A4%91%EB%B6%84%EB%A5%98).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 딥러닝 이해

In [ ]:
# MNIST data loading from Keras
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
#    독립           종속          독립          종속

# 행, 가로, 세로 -> 3차원
print(train_images.shape)    # (60000, 28, 28)
print(test_images.shape)     # (10000, 28, 28)

(60000, 28, 28)
(10000, 28, 28)


In [ ]:
# 출력 설정

print(test_images[1])
print(type(test_images))

In [ ]:
import numpy as np
np.set_printoptions(linewidth=np.inf)   # linewidth : 한줄에 출력될 문자의 최대 수

# 재출력
print(test_images[1])

# 그래프 출력
import matplotlib.pyplot as plt
plt.imshow(test_images[1])

In [ ]:
print(test_images)

In [ ]:
# 데이터 슬라이싱

my_slice = test_images[0:100]   # 특정 구간 데이터 가져옴. 여기선 0~99까지 가져온다.
print(my_slice)   # 100, 28, 28

# 3차원 데이터이므로, 위의 코드는 다음과 동일
my_slice = test_images[0:100, 0:28, 0:28]
my_slice = test_images[0:100, :, :]

In [ ]:
# Label 정보 출력

print(len(train_labels))     # 60,000
print(len(test_labels))      # 10,000

# 0~9까지의 숫자를 가지고 있다.
print(train_labels)
print(test_labels)

60000
10000
[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [ ]:
# Layer 쌓기

from keras import models, layers

model = models.Sequential()    # 모델 초기화

# 은닉층 설정
model.add(layers.Dense(256, activation='relu', input_shape=(28*28,)))

# 출력층 설정
model.add(layers.Dense(10, activation='softmax'))

은닉층 설정

3차원 데이터 2차원으로 변형 -> input_shape( , ). 값을 2차원이 아닌 3차원으로도 가능하지만 문제가 생길 수 있다.

relu : 값이 음수이면 0, 양수이면 해당 값을 출력한다. -> 음수는 딱히 필요한 값이 아니기 때문이다. (참고로 relu는 발산함)

Dense : 가중치 선을 몇개 drop해주는데, 과적합을 줄이기 위해서이다.


---


출력층 설정

10 : 출력될 값. (여기서는 숫자 범위가 0~9까지임)

softmax : 확률값을 출력하며, 0~1사이의 값으로 몯 졍규화한다. 총합은 항상 1이다. (= sigmoid 함수도 동일)

In [ ]:
# Compile model

model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

loss : 훈련데이터에서 신경망의 성능을 측정하는 손실 함수

categorical_crossentropy : 다중분류 (binary_'' : 이진분류)

optimizer : 입력된 데이터와 손실함수 기반으로 가중치를 업데이트 하는 방법(가중치 얼마나 올릴거니?)

metrics : 훈련과 테스트 과정을 모니터링할 지표. 'acc'라고도 씀.

In [ ]:
# 데이터 전처리 전

print(test_images[1,])

# 현재 데이터는 3차원이면서, 0~255사이의 숫자(색 번호)로 되어있음.
# 이를 2차원(60000, 28*28)으로 변환하고, 값이 0~1로 되도록 255로 나눔 -> 데이터 변환

In [ ]:
# 데이터 변환
train_images = train_images.reshape((60000, 28*28))   # reshape : 차원 강제 변환 (여기서는 3->2차원으로 변경)
train_images = train_images.astype('float32') / 255   # 255로 나누어 0~1사이 값 가질 수 있게 함

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

In [ ]:
train_images

In [ ]:
# 데이터 전처리 후

np.set_printoptions(linewidth=310)
print(test_images[1])

In [ ]:
# 종속변수의 원-핫 인코딩

from tensorflow.keras.utils import to_categorical

# to_categorical : 1차원 배열을 2차원 배열로 바꿔줌
train_labels = to_categorical(train_labels)     # [5 0 4 ...] -> [[0,0,0,0,0,1,0,0,0,0], ...]
test_labels = to_categorical(test_labels)       # [7 2 1 ...] -> [[0,0,0,0,0,0,0,1,0,0], ...]

print(train_labels)
print(test_labels)

In [ ]:
train_labels


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

종속변수를 원-핫 인코딩 한 이유 : 1이 있는 곳이 해당 값일 확률이 높다.

ex) 7 -> [0 0 0 0 0 0 0 0 1 0 0]  *** 10개의 원소 중 하나만 1이다.

확률 : [7] : 0.7, [8] : 0.01, [9] : 0.01

-> 확률이 어떻든 해당 값이 정답일 경우가 높기 때문에 그냥 1로 찍어줌

In [ ]:
# 데이터 학습

model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 6s 10ms/step - loss: 0.2842 - accuracy: 0.9205
Epoch 2/5
469/469 [==============================] - 3s 6ms/step - loss: 0.1238 - accuracy: 0.9635
Epoch 3/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0851 - accuracy: 0.9746
Epoch 4/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0631 - accuracy: 0.9811
Epoch 5/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0495 - accuracy: 0.9849


epochs : 머신러닝은 데이터를 한번밖에 돌려보지 않는다. 때문에 epochs를 이용해 여러번 돌릴 수 있게 만듬.

(너무 과하게 돌릴 경우 과적합 발생)

---

batch_size : 1번 모델을 훈련할 때 데이터의 양을 정해준다. 한번에 돌릴수도 있겠지만, 그렇다면 너무 오래 걸림. 이때 128개의 데이터는 랜덤으로 정해진다. 일반적으로 8~512개의 데이터 한번에 학습

In [ ]:
# 예측

test_loss, test_acc = model.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

In [2]:
# 구글 드라이브 연결

from google.colab import drive
drive.mount('/content/drive')

# 한글이 올바르게 나오게 하기 위해서는 런타임-런타임 다시시작을 눌러서 초기화 시켜주어야함

Mounted at /content/drive


In [3]:
!git https://github.com/Jung-ha1/Big_Leader_AI_Academy.git

git: 'https://github.com/Jung-ha1/Big_Leader_AI_Academy.git' is not a git command. See 'git --help'.


In [ ]:
!apt-get update
!apt-get install g++ openjdk-8-jdk

In [ ]:
!pip install JPype1
!pip install rhinoMorph

#2. 딥러닝 이해

In [1]:
# 구글 드라이브 연결

from google.colab import drive
drive.mount('/content/gdrive')

# 한글이 올바르게 나오게 하기 위해서는 런타임-런타임 다시시작을 눌러서 초기화 시켜주어야함

Mounted at /content/gdrive


In [ ]:
!apt-get update
!apt-get install g++ openjdk-8-jdk

In [ ]:
!pip install JPype1
!pip install rhinoMorph

#3. 딥러닝 이진분류

In [ ]:
# 구글 드라이브 연결

from google.colab import drive
drive.mount('/content/gdrive')

# 한글이 올바르게 나오게 하기 위해서는 런타임-런타임 다시시작을 눌러서 초기화 시켜주어야함

In [ ]:
!apt-get update
!apt-get install g++ openjdk-8-jdk

In [ ]:
!pip install JPype1
!pip install rhinoMorph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 453 kB 5.1 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 3.0 MB 5.1 MB/s 


In [ ]:
def read_data(filename, encoding='cp949'):  # 읽기   함수   정의
    with open(filename, 'r', encoding=encoding) as f:
      data = [line.split('\t') for line in f.read().splitlines()]
      data = data[1:]
    return data   # 첫   행은   헤더(id document label)일   수   있으므로   제외

def write_data(data, filename, encoding='cp949'):         # 쓰기   함수   정의
    with open(filename, 'w', encoding=encoding) as f:
      f.write(data)
data = read_data('ratings_morphed.txt' , encoding='cp949')

print(type(data))
print(len(data))
print(len(data[0])) 
print(data[0])

In [ ]:
# 데이터 줄이기
import random
import math
import numpy as np

random.shuffle(data)

part_num = math.floor(len(data) * 1/3)
data = data[:part_num]
print(len(data))

In [ ]:
# 데이터 분리
data_text = [line[1] for line in data]
data_senti = [line[2] for line in data]

from sklearn.model_selection import train_test_split
train_data_text, test_data_text, train_data_senti, test_data_senti = train_test_split(data_te xt, data_senti, stratify=data_senti)

In [ ]:
# 분리된 데이터 확인
from collections import Counter

train_data_senti_freq = Counter(train_data_senti)
print('train_data_senti_freq:',train_data_senti_freq)

test_data_senti_freq = Counter(test_data_senti)
print('test_data_senti_freq:', test_data_senti_freq)

In [ ]:
'''
원핫인코딩을 하면 컬럼의 수가 정해지기 떄문에 굳이 문장의 길이를 자르지 않아도 된다.
하지만 보통은 한다.
'''

In [ ]:
# 훈련데이터에서 검증데이터 분리

'''

validation을 최적합 모델 결과로 쓰지 않는 이유
validation은 몇번째 epoch가 가장 좋을지를 찾아주는 데이터이다.
validation이 가진 독립변수를 모델이 가지고 있던 종속변수(아마 train 데이터?)와 비교를 해서
최적의 epoch를 찾는다.
문제점은 validation이 최적의 epoch를 찾을지라도 train data는 random이기 때문에 
변화된 데이터에 따라 다른 epoch가 최적일 수도 있다.


훈련을 통해 나온 모델을 test 데이터로 돌렸을 때 기존에 나왔던 확률과 조금 차이가 난다면,
parameter를 만개가 아닌 오천개 처럼 좀 조절해준다.
그런데 여기서 문제점은 해당 test에만 적용이 잘되는거지 다른 test 데이터를 가져왔을 경우 
일반화가 어렵다.
-> 때문에 test data는 한번만 쓰는 것이 좋다. (어떤 조합이 가장 좋은지)

'''

#8. 딥러닝 다중분류

In [ ]:
# 구글 드라이브 연결

from google.colab import drive
drive.mount('/content/gdrive')

# 한글이 올바르게 나오게 하기 위해서는 런타임-런타임 다시시작을 눌러서 초기화 시켜주어야함

In [ ]:
!apt-get update
!apt-get install g++ openjdk-8-jdk

In [ ]:
!pip install JPype1
!pip install rhinoMorph

In [ ]:
# 경로 설정
chat_dir = '/content/gdrive/My Drive/pytest/chatbot/'

# 읽기 함수 정의
def read_data(filename, encoding='co949'):
  with open(filename, 'r', encoding=encoding) as f:
    data = [line.split('\t') for line in f.read().splitlines()]
    # 1로 한 이유는 값만 나오는 것이 아닌 label과 같이 어떤 값인지 알려주는 이름이 같이 출력되기 때문이다.
    data = data[1:]
  return data

# 쓰기 함수 정의
def write_data(data, filename, encoding='cp949'):
  with open(filename, 'w', encoding=encoding) as f:
    f.write(data)

In [ ]:
# 형태소 분석 준비

import rhinoMorph
rn = rhinoMorph.startRhino()    # 형태소분석기 기동

data = read_data(chat_dir + 'data.txt', encoding='cp949')

print('자료 타입: ', type(data))
print('전체 문장수: ', len(data))
print('형태소 분석 전 모습: ', data[:20])

#9. 워드임베딩